### ISSUE TITLE
Inquiry on the path forward

### ISSUE THREAD

**Issue by fanzhuyifan** [chaotic-aur/kde-git-WIP-ALPHA#2]
Hi Alexandre, thanks for the hard work!

May I ask what is the current plan for this project, moving forward? Do you plan a big rewrite in another repo, or will you be updating your code to this repo?

I am asking because I am wondering what the best way to contribute is -- whether I should start opening PRs or if I should wait until you have something more stable and more polished.

Thanks again!

**Comment by alexjp** [comment]
Hi @fanzhuyifan 

> Do you plan a big rewrite in another repo, or will you be updating your code to this repo?

Well for now, this is the repo to be used. So you can contribute to here and can start opening PRs.

My idea, is when KDE 6 (all kf+plasma+gear and arch is packaging it fully) is available, to archive this repo and move to a proper "kde-git".

The reason for this is because, I HOPE, when arch is on kde 6, the generation of PKGBUILDs will be much easier and without many changes.

In the meanwhile I also plan to make the scripts way better, either for chaotic build tools and also for users that don't really want to use chaotic-aur, but want to build kde-git themselves. (but, well, the priority is always to make the chaotic-aur build system).

Does that plan bring any issues?

**Comment by fanzhuyifan** [comment]
Sounds great! Then I am opening a bunch of issues to discuss possible improvements.
